### ISSUE TITLE
Bug: Invoke-WebRequest returns invalid variable for Set-AzureRmNetworkSecurityRuleConfig

### ISSUE THREAD

**Issue by ghost** [captainhook/AzureNetworkSecurityDynamicIP#1]
$Dyn_IP variable returned on line 33 returns a object that is not compatible with `-SourceAddressPrefix` on line 40.

`Set-AzureRmNetworkSecurityGroup : Security rule /subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/xxxx/providers/Microsoft.Network/networkSecurityGroups/xxxxx/securityRules/SSH has invalid Address 
prefix. Value provided: `

Suggest changing to
`$Dyn_IP = [system.net.dns]::GetHostByName("<your_url_here>").AddressList.IPAddressToString`

**Comment by captainhook** [comment]
Hmm... when you visit your function app URL, it should be returning just an IP in the body. I will test with your suggested change this weekend.

**Comment by ghost** [comment]
Ok I'm doing this wrong, trying to query URL directly on line 33 instead of calling IPLookup.ps1 as function app. Sorry.
