### ISSUE TITLE
Enhancement: Update Readme to include required Azure Automation Modules

### ISSUE THREAD

**Issue by ghost** [captainhook/AzureNetworkSecurityDynamicIP#3]
AzureRM.Network & AzureRM.Profile Modules required in Azure Automation Account to use as Runbook

**Comment by captainhook** [comment]
Sorry, there was an accompanying blog post which detailed this but it's offline at the moment.
I'll have adjusted the README and will have a think about anything else to add to it.

**Comment by ghost** [comment]
Thank you! Should help anyone else who isn't familar with the functions / modules required.
